services:
  gateway:
    build: .
    environment:
      - PORT=8787
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - CACHE_TTL=3600000
      - MAX_RETRIES=3
      - RETRY_DELAY=1000
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - gateway_network

networks:
  gateway_network:
    driver: bridge
